const globeSpinLottie = {
  v: "5.7.4",
  fr: 60,
  ip: 0,
  op: 120,
  w: 88,
  h: 88,
  nm: "RGuide Globe Spin",
  ddd: 0,
  assets: [],
  layers: [
    {
      ddd: 0,
      ind: 1,
      ty: 4,
      nm: "Globe",
      sr: 1,
      ks: {
        o: { a: 0, k: 100 },
        r: { a: 0, k: 0 },
        p: { a: 0, k: [44, 44, 0] },
        a: { a: 0, k: [44, 44, 0] },
        s: { a: 0, k: [100, 100, 100] },
      },
      ao: 0,
      shapes: [
        {
          ty: "gr",
          nm: "Outer Ring",
          it: [
            {
              ty: "el",
              p: { a: 0, k: [0, 0] },
              s: { a: 0, k: [68, 68] },
              nm: "Path",
            },
            {
              ty: "st",
              c: { a: 0, k: [0.1098, 0.1647, 0.2941, 1] },
              o: { a: 0, k: 100 },
              w: { a: 0, k: 3.2 },
              lc: 2,
              lj: 2,
              nm: "Stroke",
            },
            {
              ty: "tr",
              p: { a: 0, k: [44, 44] },
              a: { a: 0, k: [0, 0] },
              s: { a: 0, k: [100, 100] },
              r: { a: 0, k: 0 },
              o: { a: 0, k: 100 },
              sk: { a: 0, k: 0 },
              sa: { a: 0, k: 0 },
            },
          ],
        },
        {
          ty: "gr",
          nm: "Latitudes",
          it: [
            {
              ty: "el",
              p: { a: 0, k: [0, 0] },
              s: { a: 0, k: [56, 42] },
              nm: "Lat 1",
            },
            {
              ty: "el",
              p: { a: 0, k: [0, 0] },
              s: { a: 0, k: [56, 24] },
              nm: "Lat 2",
            },
            {
              ty: "st",
              c: { a: 0, k: [0.1098, 0.1647, 0.2941, 1] },
              o: { a: 0, k: 65 },
              w: { a: 0, k: 2 },
              lc: 2,
              lj: 2,
              nm: "Stroke",
            },
            {
              ty: "tr",
              p: { a: 0, k: [44, 44] },
              a: { a: 0, k: [0, 0] },
              s: { a: 0, k: [100, 100] },
              r: { a: 0, k: 0 },
              o: { a: 0, k: 100 },
              sk: { a: 0, k: 0 },
              sa: { a: 0, k: 0 },
            },
          ],
        },
        {
          ty: "gr",
          nm: "Longitudes Spin",
          it: [
            {
              ty: "el",
              p: { a: 0, k: [0, 0] },
              s: { a: 0, k: [16, 56] },
              nm: "Long 1",
            },
            {
              ty: "el",
              p: { a: 0, k: [0, 0] },
              s: { a: 0, k: [32, 56] },
              nm: "Long 2",
            },
            {
              ty: "el",
              p: { a: 0, k: [0, 0] },
              s: { a: 0, k: [50, 56] },
              nm: "Long 3",
            },
            {
              ty: "st",
              c: { a: 0, k: [0.1098, 0.1647, 0.2941, 1] },
              o: { a: 0, k: 72 },
              w: { a: 0, k: 2 },
              lc: 2,
              lj: 2,
              nm: "Stroke",
            },
            {
              ty: "tr",
              p: { a: 0, k: [44, 44] },
              a: { a: 0, k: [0, 0] },
              s: { a: 0, k: [100, 100] },
              r: {
                a: 1,
                k: [
                  { t: 0, s: [0], e: [360] },
                  { t: 120, s: [360], e: [0] },
                ],
              },
              o: { a: 0, k: 100 },
              sk: { a: 0, k: 0 },
              sa: { a: 0, k: 0 },
            },
          ],
        },
      ],
      ip: 0,
      op: 120,
      st: 0,
      bm: 0,
    },
  ],
} as const;

export default globeSpinLottie;
